name: CI/CD Pipeline

on:
  push:
    branches:
      - main
  pull_request:
    branches:
      - main

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Restore dependencies
    - name: Restore dependencies
      run: dotnet restore

    # Build the project
    - name: Build project
      run: dotnet build --no-restore --configuration Release

    # Run unit tests
    - name: Run tests
      run: dotnet test --no-build --verbosity normal

  deploy:
    runs-on: ubuntu-latest
    needs: build
    if: github.ref == 'refs/heads/main'

    steps:
    # Checkout code from the repository
    - name: Checkout code
      uses: actions/checkout@v3

    # Set up .NET environment
    - name: Setup .NET
      uses: actions/setup-dotnet@v3
      with:
        dotnet-version: 8.0

    # Build and publish the app
    - name: Publish app
      run: |
        dotnet publish -c Release -o ./out
        echo "Build and publish completed."

    # Deploy application (e.g., upload artifacts or deploy to Azure/AWS/GCP)
    # Replace this section with your deployment steps
    - name: Placeholder for Deployment
      run: echo "Add deployment steps here, e.g., upload to server."
